version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
  target-branch: development
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@types/faker"
    versions:
    - 5.1.5
    - 5.1.6
    - 5.1.7
    - 5.5.0
    - 5.5.1
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: faker
    versions:
    - 5.1.0
    - 5.2.0
    - 5.3.1
    - 5.4.0
    - 5.5.1
    - 5.5.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.1
  - dependency-name: "@commitlint/config-lerna-scopes"
    versions:
    - 11.0.0
    - 12.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.1
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
  - dependency-name: "@types/ws"
    versions:
    - 7.4.0
  - dependency-name: typescript
    versions:
    - 3.9.7
  commit-message:
    prefix: chore
    include: scope
  registries:
  - npm-registry-npm-pkg-github-com
