name: Continuous Integration

on: [push]

jobs:
  style:
    name: Style
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        # Github Package Registry doesn't work with Yarn.
        # --update-checksums fixes this somehow
        # see https://github.com/yarnpkg/yarn/issues/7552
        # this seems to keep causing trouble, so we use
        # npm for now.
        run: npx lerna bootstrap

      - name: Build
        run: npm run build

      - name: Lint commit messages
        run: npm run commitlint

      - name: Lint files with eslint
        run: npm run lint

      - name: Check formatting with prettier
        run: npm run prettier

  types:
    name: Types
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        # Github Package Registry doesn't work with Yarn.
        # --update-checksums fixes this somehow
        # see https://github.com/yarnpkg/yarn/issues/7552
        # this seems to keep causing trouble, so we use
        # npm for now.
        run: npx lerna bootstrap

      - name: Check Types
        # This also checks examples and tests folder for typescript errors
        run: npm run types

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        # Github Package Registry doesn't work with Yarn.
        # --update-checksums fixes this somehow
        # see https://github.com/yarnpkg/yarn/issues/7552
        # this seems to keep causing trouble, so we use
        # npm for now.
        run: npx lerna bootstrap

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.3.0
        with:
          coverageCommand: npm run coverage -- --check-coverage false
        # Also publish when tests fail
        if: always()
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  stryker-tests:
    name: Stryker Mutation tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        # Github Package Registry doesn't work with Yarn.
        # --update-checksums fixes this somehow
        # see https://github.com/yarnpkg/yarn/issues/7552
        # this seems to keep causing trouble, so we use
        # npm for now.
        run: npx lerna bootstrap

      - name: Build
        run: npm run build

      - name: Run Stryker tests
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        run: npm run test:stryker

  integration-test:
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
      - name: Checkout ula-aca-plugins
        uses: actions/checkout@v2

      - name: Checkout von-network
        uses: actions/checkout@v2
        with:
          repository: bcgov/von-network
          path: von-network
          ref: e92f15194fad5a56ac301a25f9f1d43b42470bfb

      - name: Setup VON Network
        run: |
          cd von-network
          git apply ../network-setup/fix_von_network_manage_log.patch
          ./manage build
          ./manage start

      - name: Run aca-py and aca-whr
        run: docker-compose -f network-setup/docker-compose.yml up -d --force-recreate

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        # Github Package Registry doesn't work with Yarn.
        # --update-checksums fixes this somehow
        # see https://github.com/yarnpkg/yarn/issues/7552
        # this seems to keep causing trouble, so we use
        # npm for now.
        run: npx lerna bootstrap

      - name: Run Integration Tests
        run: DOTENV_CONFIG_PATH=.env.test npm run test:integration

      - name: Export docker logs
        if: always()
        run: |
          mkdir logs
          docker-compose -f network-setup/docker-compose.yml logs --no-color > logs/docker-aca-log.txt
          cd von-network
          ./manage logs > ../logs/docker-von-log.txt

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: docker-logs
          path: logs

  release:
    name: Release
    runs-on: ubuntu-latest
    # Only release on master
    if: github.ref == 'refs/heads/master'
    needs: [style, types, unit-test, integration-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        # Github Package Registry doesn't work with Yarn.
        # --update-checksums fixes this somehow
        # see https://github.com/yarnpkg/yarn/issues/7552
        # this seems to keep causing trouble, so we use
        # npm for now.
        run: npx lerna bootstrap

      - name: Build
        run: npm run build

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ACTOR: ${{ github.actor }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: sh ./scripts/publish-packages.sh
